server:
  port: ${port:56010}

spring:
  application:
    name: quick-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a183ed00-0100-4c90-be69-06454325101c
        cluster-name: DEFAULT

logging:
  level:
    root: info
    org.springframework: info